### ISSUE TITLE
autoscaling not working because resources/requests are not specified when creating deployment

### ISSUE THREAD

**Issue by jsuchome** [bentoml/Yatai#187]
When I'm creating new deployment from Yatai UI, I have a possibility to set up autoscaling configuration; there's even a page asking for specific CPU/Memory resources

However, deployment/pod that is created does not have this information, which results in 

```the HPA was unable to compute the replica count: failed to get cpu utilization: missing request for cpu```

error and autoscaling not working. (The log line is from `kubectl describe hpa`

**Comment by yetone** [comment]
Thanks for the report! The deployment part of Yatai is now being refactored and this bug will be fixed in the next release.

In the next release, Yatai will have an operator to handle the creation of deployments, and this bug has been fixed in this operator.

**Comment by yetone** [comment]
@jsuchome  Hello, this release already fixed this bug: https://github.com/bentoml/Yatai/releases/tag/v0.2.0

**Comment by jsuchome** [comment]
Great, thanks!
