### ISSUE TITLE
Cannot push bento via CLI

### ISSUE THREAD

**Issue by amelki** [bentoml/Yatai#199]
I have installed Yatai in minikube
When I try to push a bento with `bentoml push`, I get the following error from the yatai server:

`Error: cli push failed: request failed with status code 400: {"error":"pre sign s3 upload url: get bucket yatai exist: Get \"https://yatai-minio-yatai-infra-cluster-10-109-170-163.apps.yatai.dev/yatai/?location=\": dial tcp: lookup yatai-minio-yatai-infra-cluster-10-109-170-163.apps.yatai.dev on 10.96.0.10:53: no such host"}
`

Looking at the Yatai UI, the model is successfully uploaded, but not the bento.

**Comment by yetone** [comment]
Can you give me the output of this commands?

kubectl -n yatai-components get svc

**Comment by amelki** [comment]
Here it is:

```
NAME                                                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
console                                                       ClusterIP      10.108.250.194   <none>        9090/TCP,9443/TCP            17h
minio                                                         ClusterIP      10.110.152.19    <none>        80/TCP                       17h
operator                                                      ClusterIP      10.101.44.108    <none>        4222/TCP                     17h
yatai-docker-registry                                         ClusterIP      10.100.197.6     <none>        5000/TCP                     17h
yatai-ingress-controller-ingress-nginx-controller             LoadBalancer   10.109.170.163   127.0.0.1     80:31878/TCP,443:31549/TCP   17h
yatai-ingress-controller-ingress-nginx-controller-admission   ClusterIP      10.105.159.206   <none>        443/TCP                      17h
yatai-minio-console                                           ClusterIP      10.99.66.102     <none>        9090/TCP                     17h
yatai-minio-hl                                                ClusterIP      None             <none>        9000/TCP                     17h
```

**Comment by yetone** [comment]
@amelki It looks like there is a problem with your k8s kube-dns, you can start a debug dns pod to debug your kube-dns by following these steps: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

```
kubectl exec -i -t dnsutils -- nslookup yatai-minio-yatai-infra-cluster-10-109-170-163.apps.yatai.dev
```

the correct output will like this:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1206493/158588505-b225b404-1318-42c4-9c71-e5943a7d3789.png">

**Comment by amelki** [comment]
OK thanks @yetone , I'll look into it. I'm closing the issue for now.
