### ISSUE TITLE
Poor yatai document

### ISSUE THREAD

**Issue by psc0606** [bentoml/Yatai#240]
No any document about serving and routing to diffent bentos, what's the api? I found nothing

**Comment by parano** [comment]
Thanks for the feedback @psc0606, Yatai is still under alpha release so expect some rough edges. We are currently working on user guide for Yatai, also welcome contribution if you are interested in helping out.

**Comment by parano** [comment]
Btw, if you haven't already, checkout the getting started guide here: https://github.com/bentoml/Yatai#getting-started
