### ISSUE TITLE
[Typo] Correct spelling in `kubectl` command

### ISSUE THREAD

**Issue by gaspard-met** [bentoml/Yatai#247]
In the [Getting Started part of the `readme.md`](https://github.com/bentoml/Yatai#getting-started=), section `4.`

there is a misspelled `kubectl` command : `kubeclt apply -f my_deployment.yaml` whereas it should be `kubectl apply -f my_deployment.yaml`

Would you appreciate a PR for small changes like this or would you rather do the PR yourself ?

**Comment by aarnphm** [comment]
Hi @gaspard-met. Feel free to create an PR. We are always welcoming new contributors no matter the size of the PR 😄

**Comment by parano** [comment]
This was fixed in this PR: https://github.com/bentoml/Yatai/pull/245
