### ISSUE TITLE
feat: Support defining the service account for a bentoDeployment

### ISSUE THREAD

**Issue by knechtionscoding** [bentoml/Yatai#258]
Currently when a bento is deployed via yatai it uses the default service account for the namespace. This prevents granular permissions for those bentos to access S3/GCS buckets or other data stores, and can cause other network policy issues.

Providing a string field to the bentoDeployment spec for serviceAccountName or serviceAccount would be really useful.

**Comment by yubozhao** [comment]
@KnechtionsCoding Yep that makes sense. Will make sure beef up security and stability side of things once the project settle down a little bit.

**Comment by parano** [comment]
This is now supported via the BentoDeployment CRD @knechtionscoding
