### ISSUE TITLE
Support OIDC for user Management

### ISSUE THREAD

**Issue by knechtionscoding** [bentoml/Yatai#259]
In order to not have to create users manually, and support non-yatai specific accounts. It's also more secure.

Generic feature set is:

1. Get Groups for a user
2. Assign permissions to a group instead of a user

**Comment by mts-dyt** [comment]
It would be awesome to have Keycloak intégration. 
In large scale entreprise, manually creating users is painful

**Comment by parano** [comment]
The Yatai project will focus mostly on the deployment capabilities going forward and we won't be investing in building the user management feature in the future - we recommend all users use the kubernetes RBAC for managing permissions. @knechtionscoding @mts-dyt thanks for the suggestion!
