### ISSUE TITLE
Yatai - Disable component installation if external 

### ISSUE THREAD

**Issue by mts-dyt** [bentoml/Yatai#268]
Hi bento team,

When specifying to use an external docker registry, Yatai still want to install a local registry in namespace `yatai-component`.
Is it possible to bypass this installation if we specify to use external registry: `externalDockerRegistry.enabled: true` ?
We have the same behaviour with `externalS3.enabled: true`

The only component which is bypass if not needed is PostgreSQL.

**Comment by mts-dyt** [comment]
We can also extend this behaviour to NGINX. 
In an existing cluster, we often have an existing NGINX ingress controller. Yatai is installing its own controller by if the existing controller is able to handle ingress object with classname: `Yatai-ingress`, it should be compatible

**Comment by yetone** [comment]
Thanks for your report! `v0.3.14` fixed this bug.
