### ISSUE TITLE
Grafana exposition

### ISSUE THREAD

**Issue by mts-dyt** [bentoml/Yatai#270]
Hi bento team ✋ 

When I install Monitoring component, it installs Prometheus and Grafana stack + an ingress is created on a domain own by yatai: `
http://grafana-yatai-infra-external-<IP>.apps.yatai.dev`  
In the webUI on monitoring panel, there is a link to Grafana WebUI and it refers to another entrypoint like: `https://<server>.<domain>/api/v1/clusters/default/grafana/?orgId=1`

My question is: why do we need to expose Grafana on `apps.yatai.dev`, as it is already exposed through the Yatai url (and secure by our own annotation vs the yatai internal ingress for component where we have no control).

**Comment by yetone** [comment]
@mts-dyt Yatai is designed to support multiple clusters, so grafana needs to have ingress

**Comment by mts-dyt** [comment]
Hi @yetone, thanks for your answer. 
Both URL are exposed. We can control ingress of yatai server using nginx annotation but we have no control on the one deployed from yatai-component (exposed on yatai.dev domain...). 
In a production environment, we need to have full control and visibility on public facing exposition. 
 Is it possible to only use the URL from yatai-server ?

**Comment by yetone** [comment]
@mts-dyt In the next version of yatai, grafana and prometheus and loki will no longer be installed in yatai

**Comment by yetone** [comment]
Now that yatai is no longer integrated with grafana, this requirement no longer exists
