### ISSUE TITLE
Allow for changing the tag of the initContainer Images used to build bentos

### ISSUE THREAD

**Issue by KnechtionsCoding** [bentoml/Yatai#273]
Both: https://github.com/bentoml/Yatai/blob/main/api-server/services/image_builder.go#L142 and https://github.com/bentoml/Yatai/blob/main/api-server/services/image_builder.go#L190 should be customizable to use a different tag in the event of custom requirements.

**Comment by yetone** [comment]
Thanks for your report! I fixed it in `v0.3.13`
