### ISSUE TITLE
Allow deletion of models, bentos, and deployments via yatai UI

### ISSUE THREAD

**Issue by mqk** [bentoml/Yatai#278]
Currently it appears to be impossible to delete models, bentos, or deployments from a running yatai service. Over time this leads to visual clutter and makes it more difficult to interact with yatai via UI.

Ideally the user that pushed the model/bento to yatai (or created the deployment) should be allowed to delete them. Alternatively it could be limited to just admin accounts.

**Comment by parano** [comment]
Thanks for the feedback @mqk! 

Deleting models and bentos are on our roadmap, it's a bit tricky because it may break "deployment rollback" feature in some cases, and needs to invalidate relevant deployment snapshots.

Deleting deployment is actually already supported. User have to first terminate a deployment and then it becomes possible to delete it. This can be done via the Web UI or the REST API.

**Comment by mqk** [comment]
> Deleting models and bentos are on our roadmap, it's a bit tricky because it may break "deployment rollback" feature in some cases, and needs to invalidate relevant deployment snapshots.

Makes sense. Well, great that it's being considered, even though it's tricky. 👍 

> Deleting deployment is actually already supported. User have to first terminate a deployment and then it becomes possible to delete it. This can be done via the Web UI or the REST API.

I didn't know that, but I see it now and was successfully able to delete old deployments. 💯

**Comment by eledhwen** [comment]
I see this issue has been closed as completed but as of right now it doesn't appear to be implemented yet.

Is it still on Yatai's roadmap? Is it something we can expect in the near future?

Do you have any pointers for workarounds / workflows? In the absence of such a feature we fear we might end up with large amounts of unused models / bentos from failed / iterative builds.

**Comment by matankley** [comment]
I'm interested in the ability to delete models and bentos as well.
@eledhwen  Did you find any workaround ?
@parano Is it still on the roadmap ?
