### ISSUE TITLE
External S3 fails for object > 5gb

### ISSUE THREAD

**Issue by artsparkAI** [bentoml/Yatai#284]
Tried to do `bentoml push` on a self-deployed Yatai, I get this error:
```
│ <Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>5709791785</ProposedSize><MaxSize… │ 
```

**Comment by yetone** [comment]
Thank you for your feedback, this is because the s3 put file size limit of 5gb was reached, due to the next version, yatai will solve this problem by supporting multipart uploads.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html
