### ISSUE TITLE
Error: [cli] `push` failed: request failed with status code 400: {"error":"ToModelRepositorySchemas: ToModelSchemas: GetImageName: cannot get ingress yatai-docker-registry: ingresses.networking.k8s.io \"yatai-docker-registry\" not found"}

### ISSUE THREAD

**Issue by SohelKabir** [bentoml/Yatai#292]
Following getting started tutorial from github with minikube https://github.com/bentoml/Yatai. 
I'm stuck at this step 
`bentoml push iris_classifier:latest`
I have successfully completed other step like building bento and created the admin account in yatai web interface at `http://yatai.127.0.0.1.sslip.io/`

some how docker registry service in Minikube cluster not working.
Anyone facing the issue?  i'm using docker desktop for Windows 10.

**Comment by yetone** [comment]
This is because you don't have a load balancer in your cluster, you need to check if the load balancer is working properly with the following command

kubectl -n yatai-components get svc

**Comment by SohelKabir** [comment]
![image](https://user-images.githubusercontent.com/33397287/180713161-92f249a2-7aca-4caf-aaf5-7b85c381ca8b.png)

I think loadbalancer is running!

**Comment by SohelKabir** [comment]
these two command solved problem thanks to their support team member Xipeng Guan, 

`kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io yatai-ingress-controller-ingress-nginx-admission`

`kubectl -n yatai-operators rollout restart deployment deployment-yatai-deployment-comp-operator`

according to him the problem was 

"First of all, the installation of ingress requires load balancer, so you need to manually execute minikube tunnel in advance, and secondly, the validation webhook call of ingress fails to create minio ingress, so the command just removed the webhook"

**Comment by yetone** [comment]
@SohelKabir Thank you for continuing to follow up on this issue and giving reasons, since this issue has been resolved, I'll close it for now
