### ISSUE TITLE
minio fails to deploy on EKS k8s v1.22

### ISSUE THREAD

**Issue by kaiserpelagic** [bentoml/Yatai#304]
Minio fails to deploy on k8s v1.22 because of this [issue]( https://github.com/minio/operator/issues/1048). That fix however was [reverted](https://github.com/minio/operator/pull/1059). 

Yatai should upgrade the version on Minio once this is fixed.

**Comment by yetone** [comment]
Thanks for the feedback, now Yatai doesn't integrate minio anymore, so this issue is closed
