### ISSUE TITLE
Yatai fails to deploy when underlying VM does not have /etc/localtime

### ISSUE THREAD

**Issue by kaiserpelagic** [bentoml/Yatai#308]
Not all variants of Linux have `/etc/localtime`, which will cause Yatai to fail to deploy with 

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime
```

The underlying cause is the Yatai pod is trying to mount `/etc/localtime`

```
Volumes:
  host-timezone:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
```

**Comment by lbonini94** [comment]
I tried to create a local environment to test yatai using k3s + helm and had the same problem.

**Comment by rahuldshetty** [comment]
The following PR should resolve this issue: https://github.com/bentoml/Yatai/pull/348

**Comment by lbonini94** [comment]
> The following PR should resolve this issue: #348

Hello @rahuldshetty, I'll test again as soon as possible, thanks!
