### ISSUE TITLE
AWS’s ECR get-login-password expires every 12 hours

### ISSUE THREAD

**Issue by ssheng** [bentoml/Yatai#311]
K8s to refresh secret with a cron job. Document in the AWS admin guide.

**Comment by parano** [comment]
https://skryvets.com/blog/2021/03/15/kubernetes-pull-image-from-private-ecr-registry/

**Comment by timliubentoml** [comment]
I think you might be able to use assume role, this seems like the doc for it: https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html

**Comment by parano** [comment]
> I think you might be able to use assume role, this seems like the doc for it: https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html

iam role works for simple use cases, it has two limitations: it works only for k8s cluster on AWS, and it allows all deployments on the cluster to have access to the image, there's no way to limit who can access the image
