### ISSUE TITLE
Support IAM role instead of access / secret keys to use AWS S3 bucket as custom blob storage

### ISSUE THREAD

**Issue by withsmilo** [bentoml/Yatai#316]
Hi, BentoML team.
Some companies force users not to directly own the access / secret keys for AWS S3 bucket. In this case, users can create an AWS IAM role and own the permission for S3 bucket. So it would be good if yatai also supports this scenario.

**Comment by yetone** [comment]
Thanks @withsmilo ! This is a great suggestion and we will look into it next

**Comment by withsmilo** [comment]
Thanks, @yetone . Actually this is a critical blocker for introducing BentoML-Yatai into our company. 😃

**Comment by yetone** [comment]
@withsmilo Sorry to hear that, I will solve the problem as soon as possible, thank you for your patience

**Comment by withsmilo** [comment]
Really thanks!

**Comment by yetone** [comment]
@withsmilo Yatai support AWS S3 now: https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai.html#prepare-object-storage

**Comment by withsmilo** [comment]
Hi, @yetone .
The guide page you mentioned above is using only access / secret keys to access AWS S3, but what I want is a way to use IAM roles, not that. You should reopen this issue, I think.

**Comment by zxzjim** [comment]
want to +1 on this issue, in our company we also use IAM role as the best practice. access and secret keys are not used in our K8s deployments.

**Comment by yetone** [comment]
@zxzjim Thank you for your feedback, I will add this feature ASAP

**Comment by yetone** [comment]
@withsmilo @zxzjim  Yatai already supports AWS S3 with IAM role and the documentation is available, you can use this feature by upgrading to version 1.0.5

<img width="901" alt="image" src="https://user-images.githubusercontent.com/1206493/204087170-6666e732-bb25-4641-baa6-c7d7ab04bb34.png">
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1206493/204087181-dd7bbd0a-abb7-4ac5-90c7-c2d98a5ae444.png">

https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai.html#prepare-object-storage
