### ISSUE TITLE
GKE environment bentoml deploying error

### ISSUE THREAD

**Issue by jerife** [bentoml/Yatai#323]
Hello bentoml! I have a problem in deploying model with GKE environment. 
GKE environment: 1.21.12 + Ubuntu with Docker installed

Model was deployed yesterday, but complete not yet and log in yatai ui as follow,
- get deployment bci-service: get deployment bci-service: record not found
- get deployment urls: Get "[https://10.8.0.1:443/apis/networking.k8s.io/v1/namespaces/yatai/ingresses/bci-classifier"](https://10.8.0.1/apis/networking.k8s.io/v1/namespaces/yatai/ingresses/bci-classifier%22): dial tcp 10.8.0.1:443: connect: connection refused
- list cluster yatai comps: list releases: Kubernetes cluster unreachable: Get "[https://10.8.0.1:443/version"](https://10.8.0.1/version%22): dial tcp 10.8.0.1:443: connect: connection refused
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/68190553/187805388-7a5a9c9e-b843-4e2d-8fde-0deabe35c81c.png">

10.8.0.1 cluster ip is kuberntes serivce in namespace default
<img width="1656" alt="스크린샷 2022-09-01 오전 8 58 46" src="https://user-images.githubusercontent.com/68190553/187807310-7d844b32-0e06-490b-a8f7-eea0a7383114.png">

What's the problem in my task?
Thank you to read my issue.

**Comment by yetone** [comment]
@jerife 

Thank you for your feedback. This k8s api-server inaccessible issue is a bit more complicated, you can check these things.

1. is yatai running inside this k8s cluster?
2. can you access the k8s api-server from within the cluster?
3. are the iptables in the node configured correctly?

Here is a similar issue you can refer to: https://github.com/kubernetes/kubeadm/issues/193

**Comment by jerife** [comment]
thank you for feedback :)
in my case, that problem may occured by  GKE cluster version.
So I retried same process with other verstion of GKE (kubeflow==1.8.5, GKE==1.22.12-gke.500 with emissary executor).
But now i suffer with other issue that about https://github.com/bentoml/Yatai/issues/322.
please check this issue. thank you for reading my comment :)

**Comment by yetone** [comment]
The latest version of yatai has been refactored back to kaniko, so you won't experience build image failures in GKE, so close this issue
