### ISSUE TITLE
feat: allow configuring different namespace for `yatai-builders`

### ISSUE THREAD

**Issue by ssheng** [bentoml/Yatai#350]

**Comment by jjmachan** [comment]
I was trying to take a stab at this but saw that we have something like this to configure the image builder
https://github.com/bentoml/yatai-common/blob/42f58af541c6fbb0dade50dd2e93551a09af6f74/consts/kube.go#L21-L22
```
	KubeNamespaceYataiBentoImageBuilder = "yatai-builders"
	KubeNamespaceYataiModelImageBuilder = "yatai-builders"
```

I was wondering if as a solution we can add that option here
https://github.com/bentoml/yatai-common/blob/42f58af541c6fbb0dade50dd2e93551a09af6f74/consts/env.go#L37
```
	EnvDockerImageBuilderNamespace = "DOCKER_IMAGE_BUILDER_NAMESPACE"
```
which can then be configured via the helm charts values or env vars

cc @yetone

**Comment by yetone** [comment]
@jjmachan At one time, our model and bento were built as separate images

**Comment by jjmachan** [comment]
ohh understood. 
what do u think about the proposed solution?
