### ISSUE TITLE
fix typo 

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/Yatai#370]
hi It's too minor correction, so I think it'll be good to have just a remind

~~~sh
# scripts/delete-all.sh`
...
CURRETN_CONTEXT=$(kubectl config current-context)
->CURRNET_CONTEXT
~~~

have a nice day

**Comment by yetone** [comment]
Thanks for your report! I just fixed now: https://github.com/bentoml/Yatai/pull/371
