### ISSUE TITLE
Failed to reconcile BentoDeployment

### ISSUE THREAD

**Issue by aditya624** [bentoml/Yatai#395]
Failed to reconcile BentoDeployment: DoJsonRequest Error: [GET]http://yatai.yatai-system.svc.cluster.local/api/v1/current_org: Get "http://yatai.yatai-system.svc.cluster.local/api/v1/current_org": read tcp 10.244.2.243:46536->10.97.35.56:80: read: connection reset by peer

why alway failed to deploy either ui or cli ?

**Comment by yetone** [comment]
Track the problem here: https://github.com/bentoml/yatai-deployment/issues/57

So close this issue now
