### ISSUE TITLE
Ingress default domain yatai-deployment stuck

### ISSUE THREAD

**Issue by adityapnusantara** [bentoml/Yatai#406]
Help me please. default-domain stuck at waiting ingress before failed. Ingress nginx already installed.
![Screenshot from 2022-12-09 00-56-16](https://user-images.githubusercontent.com/53865102/206528180-ffe23d4d-1046-45c1-8120-d2acabb95096.png)

**Comment by yetone** [comment]
Can you verify your ingress by following this guide? https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai_deployment.html#verify-that-this-ingress-class-is-working-properly
