### ISSUE TITLE
Cannot  update the deployment - k8s ns not writable

### ISSUE THREAD

**Issue by kvasilopoulos** [bentoml/Yatai#423]
Hi, I am trying to update the deployment in yatai to a newer bento: 
1) but when I push the update button the field "Kubernetes Namespace" is empty (while it should be yatai) and the field is not writable.
![yatai](https://user-images.githubusercontent.com/9897920/210533625-95c613bc-236f-4921-a469-5787d108566d.png)
2) Is there a way to automatically update the deployment to the newest bento without having to update the deployment? Thanks.

**Comment by kvasilopoulos** [comment]
Hi, any feedback on that? It forces me to terminate and create a new deployment whenever I want to update.

**Comment by yetone** [comment]
@kvasilopoulos Can you confirm this value on this page? It should be `yatai` or `empty`

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/1206493/211262735-d959d893-9964-48c0-87a8-dbfaae34b1b3.png">

**Comment by kvasilopoulos** [comment]
Hi, @yetone it was empty. I changed it to yatai and now it works. Thanks for the great work! 

Btw is there a way to automatically update the deployment to the newest bento without having to update the deployment manually?

**Comment by yetone** [comment]
@kvasilopoulos There are only two ways to do this, the first is through the yatai UI/API and the second is by modifying the BentoDeployment CR
