### ISSUE TITLE
Is there a way to install yatai-deployment on M1 mac?

### ISSUE THREAD

**Issue by kimkihoon0515** [bentoml/Yatai#437]
Since M1 doesn't support hyperkit driver so I launched minikube profile using this command
```
minikube start --driver=docker --cpus=4 --memory 4096 --p yatai 
```
and when i try to install yatai-deployment, an error occurs on enabling ingress addons 
![image](https://user-images.githubusercontent.com/63439911/212541113-17c6c9cb-284d-47e3-9d2c-5285317fcc8d.png)
Is there any other way to install yatai-deployment on M1 Mac?

**Comment by parano** [comment]
@kimkihoon0515 I believe this is an issue with minikube and has been resolved!
