### ISSUE TITLE
Is it impossible to register yatai-deployment if I change the namespace of yatai-system?

### ISSUE THREAD

**Issue by restato** [bentoml/Yatai#448]
When registering `yatai-deployment` to `yatai`, the following error occurs.

```
 1.6762487165919104e+09 ERROR registerYataiComponent {"func": "registerYataiComponent", "error": "DoJsonRequest Error: [POST]http://yatai.yatai-system.svc.cluster.local/api/v1/clusters/default/ yatai_components: Post \"http://yatai.yatai-system.svc.cluster.local/api/v1/clusters/default/yatai_components\": dial tcp: lookup yatai.yatai-system.svc.cluster.local
```

The URL contains the value of yatai-system namespace. Is it possible to change `yatai-system` to `yatai-system-beta`? 

>  http://yatai.yatai-system.svc.cluster.local/api/v1/clusters/default/ yatai_components
> http://yatai.yatai-system-beta.svc.cluster.local/api/v1/clusters/default/ yatai_components

**Comment by yetone** [comment]
Hello, you should set this value to the correct value: https://github.com/bentoml/yatai-image-builder/blob/main/helm/yatai-image-builder/values.yaml#L75
