### ISSUE TITLE
Error: [yatai] `login` failed: request failed with status code 403: {"message":"get api token: record not found"}

### ISSUE THREAD

**Issue by Ranjith11903952** [bentoml/Yatai#452]
I tried to log in to the yatai with, but it's throwing error. Help me establish full-fledged connection between yatai and bentoml. Please help me

**Comment by yetone** [comment]
Are you using the bentoml command line tool to log into yatai? Please check if the api token in your command is correct

**Comment by Ranjith11903952** [comment]
yes i have used two commands 
1.YATAI_INITIALIZATION_TOKEN=$(kubectl get secret yatai-env --namespace yatai-system -o jsonpath="{.data.YATAI_INITIALIZATION_TOKEN}" | base64 --decode)
2.echo "Open in browser: http://127.0.0.1:8080/setup?token=$YATAI_INITIALIZATION_TOKEN"

to login the accound i used 
bentoml yatai login --api-token {YOUR_TOKEN} --endpoint http://127.0.0.1:8080   aftet using it it showing the error 




I'm getting the error of refused connection also

**Comment by yetone** [comment]
> bentoml yatai login --api-token {YOUR_TOKEN} --endpoint http://127.0.0.1:8080/ aftet using it it showing the error

How did you get the `{YOUR_TOKEN}` in this command?

**Comment by Ranjith11903952** [comment]
echo "Open in browser: http://127.0.0.1:8080/setup?token=$YATAI_INITIALIZATION_TOKEN" this is the command to get the token 

and what may be the reasons to connections refuse

**Comment by yetone** [comment]
${YATAI_INITIALIZATION_TOKEN} is not a Yatai API KEY and cannot be used for bentoml cli login.

**Comment by Ranjith11903952** [comment]
then how to login to the yatai dashboard

**Comment by yetone** [comment]
@Ranjith11903952 The following command will show you how to login to the yatai dashboard:

```bash
helm get notes yatai -n yatai-system
```

**Comment by Ranjith11903952** [comment]
I'm getting the refused connection what may be the issue
