### ISSUE TITLE
Not able to build the Bentoml from the .mar file 

### ISSUE THREAD

**Issue by Ranjith11903952** [bentoml/Yatai#458]
I have created the .mar file over the all  files of model . I'm not able to create the bentoml deployment over the .mar file

**Comment by parano** [comment]
Hi @Ranjith11903952 - are you following a BentoML tutorial/guide using .mar model somewhere?  BentoML doesn't come with built-in support for .mar file unless you are writing your own custom runner logic for loading the model. Could you share a bit more about your set up?
