### ISSUE TITLE
does yatai support deploy bento to other cluster? 

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/Yatai#475]
hi I have a question

for example 

A cluster which is registered to yatai
-> iris Model bento in A cluster

deploy iris bento to B cluster

is it supported?

**Comment by FogDong** [comment]
You can register multiple clusters to Yatai and deploy your bentos to different clusters, is this what you want?

**Comment by FogDong** [comment]
You can manage your cluster in the cluster tab: 
<img width="194" alt="image" src="https://github.com/bentoml/Yatai/assets/15977536/f9c9f051-1064-47a3-9b0e-3b14bb4312d5">
