### ISSUE TITLE
fix trans in BentoCloud

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/Yatai#479]
BentoCloud  signup page translation

<img width="1521" alt="스크린샷 2023-06-22 오후 2 35 12" src="https://github.com/bentoml/Yatai/assets/24240623/d41552eb-90d0-4e07-9db4-18af7c4c6700">

`당신은 딱 한 걸음 멀리 있습니다!` means `you are far from one step`  I think it's awkwards

`You're just one step away! `  should be translated into `한단계만 더 진행하시면 됩니다!` to be appropriate.

**Comment by YingshuoZhang22** [comment]
fixed
