### ISSUE TITLE
Error: YAML parse error on yatai/templates/deployment.yaml

### ISSUE THREAD

**Issue by Nikitala0014** [bentoml/Yatai#489]
Hi!
When I use this script for installation I receive the following error at the end:
installing yatai 1.1.12 from helm repo bentoml...
Release "yatai" does not exist. Installing it now.
Error: YAML parse error on yatai/templates/deployment.yaml: error converting YAML to JSON: yaml: line 10: did not find expected key

Does anyone know the reason of that and how to solve it?
Thanks

**Comment by yetone** [comment]
‌‌I'm very sorry, the latest version v1.1.13 has already fixed this issue!

**Comment by 106firestarter** [comment]
I confirm that it is working now! Thank you for the quick reply!!

**Comment by Nikitala0014** [comment]
Oh, great! Thank's
