### ISSUE TITLE
Autoscaling LLM

### ISSUE THREAD

**Issue by AIApprentice101** [bentoml/Yatai#500]
Thank you for the great repo.

I have been using OpenLLM to serve an LLM, and I'm working on deployment in GKE using Yatai. Can I ask what's the recommended Autoscaling metric? I'm using vLLM as backend, the GPU utilization remains at 90%, so I can't use it for Autoscale. Thanks.

**Comment by parano** [comment]
Hi @AIApprentice101, we recommend concurrency based auto-scaling for LLMs. This is currently not available in Yatai.

**Comment by AIApprentice101** [comment]
got it thanks.
